"""
default.py — Entry point for plugin.video.nuisync (NuiSync~)

Shows a cute menu:
    - Host (auto-connect via session code)
    - Join via Session Code
    - Join via Direct IP (legacy / Hamachi fallback)
    - Toggle Overlay / Disconnect (when active)

Stores the chosen action into a window property so the background
service (service.py) can pick it up.

Also handles the toggle_overlay argument so it can be bound to a
keyboard/remote shortcut via Kodi's keymap system or Favourites:
    RunScript(plugin.video.nuisync,toggle_overlay)
"""

import sys

import xbmc
import xbmcgui
import xbmcaddon

ADDON = xbmcaddon.Addon("plugin.video.nuisync")
ADDON_NAME = ADDON.getAddonInfo("name")


def main():
    win = xbmcgui.Window(10000)

    # ---- Handle RunScript argument (for keymap / favourites) ----
    if len(sys.argv) > 1 and sys.argv[1] == "toggle_overlay":
        win.setProperty("nuisync.toggle_overlay", "true")
        return

    is_active = win.getProperty("nuisync.active") == "true"

    # ---- Active session menu ----
    if is_active:
        options = [
            "Show / Hide Overlay~",
            "Disconnect",
        ]
        choice = xbmcgui.Dialog().select(ADDON_NAME, options)
        if choice == 0:
            win.setProperty("nuisync.toggle_overlay", "true")
        elif choice == 1:
            win.setProperty("nuisync.role", "disconnect")
        return

    # ---- New session menu ----
    options = [
        "Host a NuiSync session~",
        "Join with Session Code~",
        "Join with Direct IP (Hamachi/LAN)",
    ]
    choice = xbmcgui.Dialog().select(ADDON_NAME, options)

    if choice == 0:
        # Host — the session code will be generated by service.py
        # and shown on the overlay once ready
        win.setProperty("nuisync.role", "host")

    elif choice == 1:
        # Join via session code
        code = xbmcgui.Dialog().input(
            "Enter Session Code~",
            type=xbmcgui.INPUT_ALPHANUM,
        )
        if not code:
            return
        # Clean up the code
        code = code.strip().upper().replace(" ", "").replace("-", "")
        if len(code) != 10:
            # Try with dashes removed already
            xbmcgui.Dialog().ok(
                ADDON_NAME,
                "Invalid code. Codes look like XXXXX-XXXXX (10 characters)~")
            return
        # Format nicely
        formatted = "%s-%s" % (code[:5], code[5:])
        win.setProperty("nuisync.role", "join_code")
        win.setProperty("nuisync.session_code", formatted)

    elif choice == 2:
        # Join via direct IP (legacy Hamachi / LAN / manual port forward)
        saved_ip = ADDON.getSetting("hamachi_ip") or "25.0.0.1"
        ip = xbmcgui.Dialog().input(
            "Enter Host's IP~",
            defaultt=saved_ip,
            type=xbmcgui.INPUT_IPADDRESS,
        )
        if not ip:
            return
        ADDON.setSetting("hamachi_ip", ip)
        win.setProperty("nuisync.role", "join")
        win.setProperty("nuisync.host_ip", ip)


if __name__ == "__main__":
    main()